-- 科目テーブル
INSERT INTO subjects (name, created_at) VALUES
('数学', NOW()),
('英語', NOW()),
('国語', NOW()),
('理科', NOW()),
('社会', NOW());

-- 科目別成績テーブル
INSERT INTO subject_results (user_id, subject_id, score, created_at) VALUES
('hanako.sato', 1, 85, NOW()),
('hanako.sato', 2, 90, NOW()),
('hanako.sato', 3, 78, NOW()),
('hanako.sato', 4, 88, NOW()),
('hanako.sato', 5, 92, NOW()),
('ichiro.suzuki', 1, 75, NOW()),
('ichiro.suzuki', 2, 80, NOW()),
('ichiro.suzuki', 3, 70, NOW()),
('ichiro.suzuki', 4, 82, NOW()),
('ichiro.suzuki', 5, 76, NOW()),
('misaki.takahashi', 1, 95, NOW()),
('misaki.takahashi', 2, 89, NOW()),
('misaki.takahashi', 3, 94, NOW()),
('misaki.takahashi', 4, 91, NOW()),
('misaki.takahashi', 5, 87, NOW()),
('kenta.tanaka', 1, 65, NOW()),
('kenta.tanaka', 2, 70, NOW()),
('kenta.tanaka', 3, 68, NOW()),
('kenta.tanaka', 4, 72, NOW()),
('kenta.tanaka', 5, 74, NOW()),
('ai.nakamura', 1, 88, NOW()),
('ai.nakamura', 2, 92, NOW()),
('ai.nakamura', 3, 85, NOW()),
('ai.nakamura', 4, 90, NOW()),
('ai.nakamura', 5, 93, NOW()),
('naoki.kobayashi', 1, 78, NOW()),
('naoki.kobayashi', 2, 82, NOW()),
('naoki.kobayashi', 3, 80, NOW()),
('naoki.kobayashi', 4, 79, NOW()),
('naoki.kobayashi', 5, 81, NOW()),
('mayu.kato', 1, 91, NOW()),
('mayu.kato', 2, 87, NOW()),
('mayu.kato', 3, 93, NOW()),
('mayu.kato', 4, 89, NOW()),
('mayu.kato', 5, 90, NOW()),
('sho.yoshida', 1, 84, NOW()),
('sho.yoshida', 2, 86, NOW()),
('sho.yoshida', 3, 88, NOW()),
('sho.yoshida', 4, 85, NOW()),
('sho.yoshida', 5, 87, NOW());